# dataset_config_path:
# encoder_config_path:
# segmentor_config_path:
# augmentation_config_path:
resume_from: null
finetune: False
eval_dir: null
use_wandb: false
work_dir: './work-dir'
seed: 0
num_workers: 8
batch_size: 8
epochs: 80
limited_label: -1
fp16: false
bf16: false
ckpt_interval: 40
eval_interval: 5
log_interval: 10
rank: -1
local_rank: -1
world_size: 1
local_world_size: 1