dataset_config_path: configs/datasets/mados.yaml
encoder_config_path: configs/foundation_models/ssl4eo_moco.yaml
segmentor_config_path: configs/segmentors/upernet.yaml
augmentation_config_path: configs/augmentations/segmentation_default.yaml

resume_from: null
finetune: False
eval_dir: null
use_wandb: false
work_dir: './work-dir'
seed: 0
num_workers: 8
batch_size: 8
epochs: 80
fp16: false
bf16: false
ckpt_interval: 20
eval_interval: 5
log_interval: 10
rank: -1
local_rank: -1
world_size: 1
local_world_size: 1