name: gfm-bench8
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - geopandas
  - numpy>=2.0
  - pillow
  - pytorch>=2.1
  - rasterio
  - scikit-learn
  - tensorboard
  - torchaudio
  - torchvision
  - tqdm
  - timm
  - einops
  - open-clip-torch
  - rioxarray
  - pytorch-cuda=11.8
  - gdown
  - ptflops
  - fastai::opencv-python-headless
  - google-cloud-storage
  - omegaconf
  - pydataverse