encoder_name: CROMA_SAR_Encoder
foundation_model_name: CROMA_SAR_large
encoder_weights: ./pretrained_models/CROMA_large.pt
download_url: https://huggingface.co/antofuller/CROMA/resolve/main/CROMA_large.pt
temporal_input: False


num_layers: 24
embed_dim: 1024
input_size: 120  # the paper uses 120

encoder_model_args:
  size: 'large'
  image_resolution: 120

input_bands:
  sar:
    - VV
    - VH

output_layers:
  - 3
  - 5
  - 7
  - 11
