encoder_name: SSL4EO_MAE_OPTICAL_Encoder
foundation_model_name: ssl4eo_mae_vit_small_patch16
encoder_weights: ./pretrained_models/b_baseViT_gmae_fmow_single_temporal_ab_fcpt.pth
download_url: https://drive.google.com/uc?id=1QTBKl1asxgQCNd6bO2azXZNPfoQ3Sazv&export=download&confirm=yes

temporal_input: False

num_layers: 12
embed_dim: 768
input_size: 224

encoder_model_args:
  img_size: 224
  in_chans: 3
  embed_dim: 768
  patch_size: 16
  num_heads: 12
  depth: 12
  mlp_ratio: 4

input_bands:
  optical:
    - B4
    - B3
    - B2


output_layers:
  - 3
  - 5
  - 7
  - 11
