encoder_name: UNet_Encoder
encoder_weights: ''
temporal_input: True

input_size: 256
embed_dim: 3

encoder_model_args:
  topology: [64, 128, 256, 512,]
  in_channels: 3

input_bands:
  optical:
    - B2
    - B3
    - B4