train: 
  - _target_: pangaea.engine.data_preprocessor.SegPreprocessor
    # overwritten in run
    dataset: null
    encoder: null

  - _target_: pangaea.engine.data_preprocessor.NormalizeMeanStd
    # overwritten in run
    dataset: null
    encoder: null

  - _target_: pangaea.engine.data_preprocessor.ResizeToEncoder
    # overwritten in run
    dataset: null
    encoder: null

test: 
  - _target_: pangaea.engine.data_preprocessor.SegPreprocessor
    # overwritten in run
    dataset: null
    encoder: null

  - _target_: pangaea.engine.data_preprocessor.NormalizeMeanStd
    # overwritten in run
    dataset: null
    encoder: null

  - _target_: pangaea.engine.data_preprocessor.ResizeToEncoder
    # overwritten in run
    dataset: null
    encoder: null

