_target_: pangaea.datasets.geobench.mbigearthnet.mBigEarthNet
dataset_name: mBigEarthNet
root_path: ${oc.env:GEO_BENCH_DIR}/classification_v1.0/m-bigearthnet   # ensure sys env var GEO_BENCH_DIR exist
download_url: "recursix/geo-bench-1.0"
auto_download: True
ignore_index: -100
num_classes: 43
img_size: 120
multi_temporal: False
multi_modal: False

bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B11
    - B12

classes:  ['']
distribution: [0,]

# data stats
data_mean:
  optical: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

data_std:
  optical: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
data_min:
  optical: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
data_max:
  optical: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]