_target_: pangaea.datasets.geobench.mbrickkiln.mBrickKiln
dataset_name: mBrickKiln
root_path: ${oc.env:GEO_BENCH_DIR}/classification_v1.0/m-brick-kiln
download_url: "recursix/geo-bench-1.0"
auto_download: True

num_classes: 2
img_size: 64
multi_temporal: False
multi_modal: False

ignore_index: -100
classes:  ['', '']
distribution: [0, 0]
bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B10
    - B11
    - B12
data_mean:
  optical: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
data_std:
  optical: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
data_min:
  optical: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
data_max:
  optical: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]