_target_: pangaea.datasets.geobench.mpv4ger.mPv4ger
dataset_name: mPv4ger
root_path: ${oc.env:GEO_BENCH_DIR}/classification_v1.0/m-pv4ger
download_url: "recursix/geo-bench-1.0"
auto_download: True

num_classes: 2
img_size: 320
multi_temporal: False
multi_modal: False

ignore_index: -100
classes:  ['', '']
distribution: [0, 0]

# data stats
bands:
  optical:
    - B4
    - B3
    - B2

data_mean:
  optical: [0.0, 0.0, 0.0]
data_std:
  optical: [0.0, 0.0, 0.0]
data_min:
  optical: [0.0, 0.0, 0.0]
data_max:
  optical: [0.0, 0.0, 0.0]