_target_: pangaea.datasets.geobench.mso2sat.mSo2Sat
dataset_name: mSo2Sat
root_path: ${oc.env:GEO_BENCH_DIR}/classification_v1.0/m-so2sat
download_url: "recursix/geo-bench-1.0"
auto_download: True


num_classes: 17
img_size: 32
multi_temporal: False
multi_modal: False

bands:
  optical:
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B11
    - B12
    
ignore_index: -100
classes:  ['', '', '', '', '', '', '', '', '', '', '', '','', '', '', '', '']
distribution: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

data_mean:
  optical: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

data_std:
  optical: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
data_min:
  optical: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
data_max:
  optical: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]