encoder_name: ssl4eo_dino
encoder_weights: ./pretrained_models/B13_vits16_dino_0099.pth
download_url: https://drive.google.com/uc?id=1CseO5vvMReGlAulm5o4ZgbjUgj8VlAH7&export=download&confirm=yes

encoder_model_args:
  img_size: 224
  in_chans: 13
  #backbone parameters (mainly ViT)
  embed_dim: 384
  patch_size: 8
  num_heads: 12
  depth: 12
  mlp_ratio: 4
  global_pool: True
  # spectral_gpt specific
  num_frames: 1 
  t_patch_size: 3
  #satlas specific
  multi_image: False
  backbone: Backbone.SWINB
  #prithvi specific
  tubelet_size: 1
  #gfm specific
  window_size: 4
  drop_path_rate: 0.1
  #croma specific
  modality: "joint" # support also both and radar
  # dofa specific
  wave_list: [1,1,1]