encoder_name: croma
encoder_weights: ./pretrained_models/CROMA_large.pt
download_url: https://huggingface.co/antofuller/CROMA/resolve/main/CROMA_large.pt

encoder_model_args:
  img_size: 120
  in_chans: 12
  img_size: 120
  embed_dim: 1024
  patch_size: 8
  num_heads: 16
  depth: 24
  modality: "optical" # support also "joint" and "SAR"

input_bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8a
    - B9
    - B11
    - B12