encoder_name: dofa
encoder_weights: ./pretrained_models/DOFA_ViT_base_e100.pth
download_url: https://huggingface.co/XShadow/DOFA/resolve/main/DOFA_ViT_base_e100.pth

encoder_model_args:
  img_size: 224
  embed_dim: 768

input_bands:
  optical:
    - B4
    - B3
    - B2

