encoder_name: scale_mae
encoder_weights: ./pretrained_models/scalemae-vitlarge-800.pth
download_url: https://github.com/bair-climate-initiative/scale-mae/releases/download/base-800/scalemae-vitlarge-800.pth

encoder_model_args:
  img_size: 224
  embed_dim: 1024
  in_chans: 3
  patch_size: 16
  global_pool: True

input_bands:
  optical:
    - B4
    - B3
    - B2
