encoder_name: ssl4eo_moco
encoder_weights: ./pretrained_models/B13_vits16_moco_0099.pth
download_url: https://drive.google.com/uc?id=1LREGuI6w7Gq6Xm0jFQdxxtp8QkmLvJWk&export=download&confirm=yes

encoder_model_args:   
  img_size : 224
  patch_size: 16
  embed_dim: 384
  depth: 12
  num_heads: 6 
  mlp_ratio: 4
  in_chans: 13

input_bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8a
    - B9
    - B10
    - B11
    - B12