encoder_name: ssl4eo_data2vec
encoder_weights: ./pretrained_models/B13_vits16_data2vec_0099_ckpt.pth
download_url: https://drive.google.com/uc?id=1VbIGBwzZYndv4v1vx9FiD6IP-YwsHEns&export=download&confirm=yes

encoder_model_args:
  img_size: 224
  in_chans: 13
  embed_dim: 384

input_bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8a
    - B9
    - B10
    - B11
    - B12