train: true
work_dir: ""
seed: 234
use_wandb: false
wandb_run_id: null

# TRAINING
num_workers: 1
batch_size: 32


# EXPERIMENT
finetune: false
ckpt_dir: null
limited_label_train: 1
limited_label_val: 1
limited_label_strategy: stratified  # Options: stratified, oversampled, random
stratification_bins: 3 #  number of bins for stratified sampling, only for stratified



defaults:
  - task: ???
  - dataset: ???
  - encoder: ???
  - decoder: ???
  - preprocessing: ???
  - criterion: ???
  - lr_scheduler: multi_step_lr
  - optimizer: adamw
  - _self_ 
