train:
  SegPreprocessor:
  RandomCropToEncoder:
  RandomFlip:
    ud_probability: 0.3
    lr_probability: 0.3
  NormalizeMeanStd: 
  # ColorAugmentation:
  #   brightness: 0.3 
  #   contrast: 0.5 # distance to 1
  #   br_probability: 0.3
  #   ct_probability: 0.3

test:
  SegPreprocessor:
  NormalizeMeanStd:
  Tile: