train:
  SegPreprocessor: ~
  NormalizeMeanStd: ~
  ResizeToEncoder: ~
  # RandomFlip:
  #   ud_probability: 0.3
  #   lr_probability: 0.3
test:
  SegPreprocessor: ~
  NormalizeMeanStd: ~
  ResizeToEncoder: ~
