dataset_name: BioMassters
root_path: /geomatics/gpuserver-0/vmarsocci/biomassters
download_url: #https://huggingface.co/datasets/ibm-nasa-geospatial/hls_burn_scars/resolve/main/hls_burn_scars.tar.gz?download=true
auto_download: False
img_size: 256
multi_temporal: 12
multi_modal: True


# classes
# ignore_index: -1
num_classes: 1
classes:
  - regression
distribution:
  - 1.
#   - 0.2
#   - 0.2
#   - 0.2
#   - 0.2
#   - 0.2

bands:
  optical:
    - B2
    - B3
    - B4
    # - B5
    # - B6
    # - B7
    # - B8
    # - B8a
    # - B11
    # - B12
  sar:
    - ASC_VV
    - ASC_VH
    - DSC_VV
    - DSC_VH

data_mean:
  optical:
    - 66.7703
    - 88.4452
    - 85.1047
  # sar:

data_std:
  optical:
    - 48.3066
    - 51.9129
    - 62.7612
  # sar: